# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- Gemfile
- Gemfile.lock
- README.md
- vendor

# Set plugins
plugins:
- jekyll-default-layout
- jekyll-feed
- jekyll-mentions
- jekyll-menus
- jekyll-paginate
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
- jemoji

# Site settings
url: 'https://www.healthwildcatters.com'
baseurl: ''
title: 'Health Wildcatters'
description: ''
permalink: pretty
cloudinaryurl: 'https://res.cloudinary.com/health-wildcatters/image/upload'

collections:
  - co-founders
  - mentors
  - news
  - sponsors
  - staff
