# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- Gemfile
- Gemfile.lock
- README.md
- vendor

# Set plugins
plugins:
- jekyll-default-layout
- jekyll-feed
- jekyll-mentions
- jekyll-menus
- jekyll-paginate
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
- jemoji

# Site settings
baseurl: ''
cloudinaryurl: 'https://res.cloudinary.com/health-wildcatters/image/upload'
description: ''
google_analytics: 'UA-40198461-1'
logo: '/assets/img/logo.svg'
permalink: pretty
title: 'Health Wildcatters'
url: 'https://www.healthwildcatters.com'

collections:
  co-founders:
    output: true
  mentors:
    output: true
  news:
    output: true
  portfolio:
    output: true
  sponsors:
    output: true
  staff:
    output: true
