# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- Gemfile
- Gemfile.lock
- README.md
- vendor

# Set plugins
plugins:
- jekyll-default-layout
- jekyll-feed
- jekyll-mentions
- jekyll-menus
- jekyll-paginate
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
- jemoji

# Site settings
url: 'https://mydomain.com'
baseurl: ''
title: 'Health Wildcatters'
description: ''
permalink: pretty

# Pagination
paginate: 5
paginate_path: news/page:num

# Collections
collections:
  news:
    title: News
    output: true
