[build]
  command = "jekyll build"
  publish = "_site"

[build.environment]
  JEKYLL_ENV = "production"

[[redirects]]
  from = "https://healthwildcatters.netlify.com/*"
  to = "https://www.healthwildcatters.com/:splat"
  status = 301
