---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: _mentors
  label: Mentors
  create: all
  match: "**/*"
  templates:
  - person
- type: directory
  path: _news
  label: News
  create: all
  match: "**/*"
  templates:
  - news
- type: jekyll-pages
  label: Pages
  create: all
  templates:
  - blocks
  - page
upload_dir: ''
public_path: https://res.cloudinary.com/health-wildcatters/image/upload
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
