---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: _co-founders
  label: Co-founders
  create: all
  match: "**/*"
  templates:
  - person
- type: directory
  path: _hia
  label: HIA
  create: all
  match: "**/*"
  templates:
  - company-organization
- type: directory
  path: _mentors
  label: Mentors
  create: all
  match: "**/*"
  templates:
  - person
- type: directory
  path: _news
  label: News
  create: all
  match: "**/*"
  templates:
  - news
- type: directory
  path: _portfolio
  label: Portfolio companies
  create: all
  match: "**/*"
  templates:
  - company-organization
- type: directory
  path: _sponsors
  label: Sponsors
  create: all
  match: "**/*"
  templates:
  - company-organization
- type: directory
  path: _staff
  label: Staff
  create: all
  match: "**/*"
  templates:
  - person
- type: jekyll-pages
  label: Pages
  create: all
  templates:
  - blocks
  - page
upload_dir: assets/img/uploads
public_path: "/assets/img/uploads"
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
